#graphql
scalar JSON

type Query {
  #user
  getAllUsers: [User!]

  #exercise
  getAllExercises: [Exercise]
}
type Mutation {
  #user
  addUser(input: AddUserInput): AddUserResponse!

  #exercise
}

interface MutationResponse {
  isSuccess: Boolean!
  error: JSON
}
