type User {
  id: ID!
  email: String!
  name: String
  username: String
  logo: String
  is_deleted: Boolean
  deleted_by: Int
  created_at: String
  created_by: Int
  updated_at: String
  updated_by: Int
  metadata: JSON
}
input AddUserInput {
  username: String
  password: String!
  email: String!
}

type AddUserResponse implements MutationResponse {
  isSuccess: Boolean!
  data: User
  error: JSON
}
